// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package folder

import (
	"github.com/koujiman/go-clean-template/infrastructure/repository"
	"github.com/koujiman/go-clean-template/usecase/folder"
	"gorm.io/gorm"
)

// Injectors from injector.go:

func InjectFolder(db *gorm.DB) *FolderController {
	folderRepository := repository.ProvideFolderRepository(db)
	createFolderUseCase := usecase.ProvideCreateFolderUseCase(folderRepository)
	getAllFoldersUseCase := usecase.ProvideGetAllFoldersUseCase(folderRepository)
	folderController := ProvideFolderController(createFolderUseCase, getAllFoldersUseCase)
	return folderController
}
